package com.revature.Project0.models;

import jakarta.persistence.*;
import lombok.Data;

@Entity // This annotation tells us that the class is going to be an entity mapped to
        // the DB.
@Data // This annotation from Lombok lib will auto-generate the getters and setters
      // for us.
@Table(name = "items") // The table annotation specifies the name of the table in our DB that is going
                       // to correspond to our entity.
public class Item {
    @Id // Makes the id field the primary key of the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Tells us that the id value is auto-generated by the DB.
    private Long id;

    // The @Column annotation is used to specify the properties of a column in a
    // table.
    // These fields are nullable = false, which means they can't be null in the DB.
    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String description;

    @Column(nullable = false)
    private boolean status;

    // The @ManyToOne annotation indicates the relationship between the item and
    // user.
    // A user can have many items.
    @ManyToOne
    // The @JoinColumn specifies the foreign key column name in the items table
    // that references the primary key of the users table.
    @JoinColumn(name = "user_id")
    private User user;
}